In [4]:
from api.scripts.data_load.download_enderecos_lotes import download_enderecos_lotes

In [5]:
print('oi')

oi

In [6]:
df = download_enderecos_lotes()

Arquivo 'enderecos_lotes.parquet' já existe. Carregando dados do arquivo...

In [7]:
df.head()

,cd_identificador,cd_logradouro,nm_logradouro_completo,cd_numero_porta,tx_complemento_endereco
0,1957324,048046,R CESARIO ALVIM,716,
1,1957325,048046,R CESARIO ALVIM,720,BELENZINHO
2,1957326,020583,R ARAPANEMA,57,
3,1957327,031216,R BENEDITA SA BARBOSA,20,
4,1957333,089443,AV IBIRAPUERA,3242,INDIANOPOLIS

In [31]:
df[df['cd_identificador']<1957325]

,cd_identificador,cd_logradouro,nm_logradouro_completo,cd_numero_porta,tx_complemento_endereco
0,1957324,048046,R CESARIO ALVIM,716,

In [32]:
df['cd_identificador'].nunique()

1612965

In [33]:
df['cd_identificador'].isnull().any()

np.False_

In [36]:
df[df['cd_identificador']==2031329]

Empty DataFrame
Columns: [cd_identificador, cd_logradouro, nm_logradouro_completo, cd_numero_porta, tx_complemento_endereco]
Index: []

In [35]:
df['cd_identificador'].min()

np.int64(1957324)

In [34]:
df['cd_identificador'].duplicated().any()

np.False_

In [16]:
df['cd_identificador'].dtype

dtype('int64')

In [12]:
df[(df['cd_logradouro']=="058874")]['cd_numero_porta'].unique()

<ArrowStringArray>
['846', '275', '886', '263', '237', '310', '671', '641', '645', '764', '338',
 '789', '195', '553', '353', '856', '791', '243',  '67',  '83', '156', '530',
 '552', '729', '698', '863', '829', '541', '580',  '98', '619', '569', '847',
 '845', '151', '326', '638', '260', '114', '561', '628', '632', '604', '269',
 '213', '566', '784', '651', '303', 'S/N', '232', '253',  '91', '211', '834',
 '767', '759', '842', '126', '680', '779', '674', '578', '745', '650',  '40',
 '616', '258', '525', '311', '272', '314', '235', '219', '735', '143', '778',
 '337', '773', '285', '699', '681', '547', '135', '304', '855', '200', '800',
 '590', '318', '837', '300', '692', '518', '528']
Length: 95, dtype: str

In [15]:
df[(df['cd_logradouro']=="058874")&(df['cd_numero_porta']=='40')]

,cd_identificador,cd_logradouro,nm_logradouro_completo,cd_numero_porta,tx_complemento_endereco
54877,2025081,058874,R MAJ DIOGO,40,54 ATE 70

In [6]:
df['cd_numero_porta'].replace('S/N', 0).astype(int)

0           716
1           720
2            57
3            20
4          3242
           ...
1612960       0
1612961       9
1612962    1411
1612963      21
1612964      23
Name: cd_numero_porta, Length: 1612965, dtype: int64

In [9]:
df.shape

(1612965, 5)

In [11]:
df['cd_identificador'].duplicated().any()

np.False_

In [5]:
df['nm_logradouro_completo'].str.split(' ').str[0].value_counts()

nm_logradouro_completo
R      1402237
AV      134638
TV       44246
ES        9586
PC        8667
AL        7050
PS        2210
VP        1841
LG         726
RP         388
VE         320
VIA        281
PQ         203
TVP        138
PSP        106
CM          97
VL          85
RV          77
RPJ         68
LD          43
AC          43
VCP         33
VEP         25
VER         23
PT           8
VD           7
BC           7
CP           7
PCR          7
TPJ          6
PQM          5
SV           5
VLP          3
VES          3
CV           2
ESP          1
CMP          1
Name: count, dtype: int64

In [17]:
df['nm_logradouro_completo'].str.split(' ').str[0].unique().tolist()

['R',
 'AV',
 'AL',
 'TV',
 'LG',
 'PC',
 'VL',
 'VP',
 'PS',
 'LD',
 'PQ',
 'VE',
 'VD',
 'PQM',
 'BC',
 'TVP',
 'VER',
 'RP',
 'ES',
 'PSP',
 'VEP',
 'RV',
 'VIA',
 'VCP',
 'PT',
 'TPJ',
 'AC',
 'ESP',
 'SV',
 'VLP',
 'CM',
 'CMP',
 'RPJ',
 'CP',
 'PCR',
 'VES',
 'CV']

In [7]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 1613193 entries, 0 to 1613192
Data columns (total 4 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   cd_identificador        1613193 non-null  int64
 1   cd_logradouro           1613193 non-null  str
 2   nm_logradouro_completo  1613193 non-null  str
 3   cd_numero_porta         1613193 non-null  str
dtypes: int64(1), str(3)
memory usage: 89.5 MB

In [8]:
df.shape

(1613193, 4)

In [9]:
df['nm_logradouro_completo'].str.isupper().all()

np.True_

In [10]:
from api.services.fuzzy_iptu_address_search.address_match import AddressMatcher

In [11]:
matcher = AddressMatcher(df)

In [12]:
matcher.find_matches("Rua João de Barro, 123")

[{'logradouro': 'R JOA',
  'score': 90.0,
  'input_processado': 'R JOAO DE BARRO 123'},
 {'logradouro': 'R JOAO DE BARROS',
  'score': 85.71,
  'input_processado': 'R JOAO DE BARRO 123'},
 {'logradouro': 'R ARAPANEMA',
  'score': 85.5,
  'input_processado': 'R JOAO DE BARRO 123'},
 {'logradouro': 'R HUMBERTO I',
  'score': 85.5,
  'input_processado': 'R JOAO DE BARRO 123'},
 {'logradouro': 'R CEL DIOGO',
  'score': 85.5,
  'input_processado': 'R JOAO DE BARRO 123'}]

In [13]:
matcher.find_matches("Avenida Paulista")

[{'logradouro': 'AV PAULISTA',
  'score': 100.0,
  'input_processado': 'AV PAULISTA'},
 {'logradouro': 'R BANDEIRA PAULISTA',
  'score': 85.71,
  'input_processado': 'AV PAULISTA'},
 {'logradouro': 'R BERNARDA PAULISTA',
  'score': 85.71,
  'input_processado': 'AV PAULISTA'},
 {'logradouro': 'AV CACHOEIRA PAULISTA',
  'score': 85.71,
  'input_processado': 'AV PAULISTA'},
 {'logradouro': 'R TIJUCA PAULISTA',
  'score': 85.71,
  'input_processado': 'AV PAULISTA'}]

In [14]:
matcher.get_full_logradouro_info("AV PAULISTA")

         cd_identificador cd_logradouro nm_logradouro_completo cd_numero_porta
160               1957529        156566            AV PAULISTA            1267
1602              1959342        156566            AV PAULISTA               7
3686              1961928        156566            AV PAULISTA            1106
6156              1964984        156566            AV PAULISTA            1500
9055              1968540        156566            AV PAULISTA             407
15684             1976782        156566            AV PAULISTA             949
17665             1979231        156566            AV PAULISTA             900
20758             1983056        156566            AV PAULISTA             709
22390             1985082        156566            AV PAULISTA            1374
30158             1994702        156566            AV PAULISTA             436
31454             1996300        156566            AV PAULISTA             119
34575             2000136        156566            AV PAULISTA             393
36176             2002080        156566            AV PAULISTA            1345
47757             2016280        156566            AV PAULISTA            1000
48852             2017639        156566            AV PAULISTA             750
55120             2025347        156566            AV PAULISTA            1373
57977             2028864        156566            AV PAULISTA             548
58478             2029482        156566            AV PAULISTA             329
59186             2030375        156566            AV PAULISTA             392
59390             2030635        156566            AV PAULISTA            1510
59989             2031388        156566            AV PAULISTA             777
60226             2031700        156566            AV PAULISTA             810
61091             2032711        156566            AV PAULISTA             412
61180             2032825        156566            AV PAULISTA             227
63577             2035828        156566            AV PAULISTA             200
64026             2036386        156566            AV PAULISTA             867
64622             2037148        156566            AV PAULISTA             486
66471             2039441        156566            AV PAULISTA             633
72124             2046418        156566            AV PAULISTA             664
73018             2047530        156566            AV PAULISTA             149
73189             2047738        156566            AV PAULISTA              52
73822             2048512        156566            AV PAULISTA             735
76927             2052399        156566            AV PAULISTA             778
81407             2057890        156566            AV PAULISTA            1405
83549             2060560        156566            AV PAULISTA            1079
86336             2063952        156566            AV PAULISTA            1257
91100             2147060        156566            AV PAULISTA             S/N
95979             2152545        156566            AV PAULISTA            1919
95980             2152546        156566            AV PAULISTA            1941
97145             2153846        156566            AV PAULISTA            2421
109402            2167568        156566            AV PAULISTA            2100
117283            2176388        156566            AV PAULISTA            1682
121366            2180949        156566            AV PAULISTA            2150
123415            2183244        156566            AV PAULISTA            1963
126773            2187039        156566            AV PAULISTA            2295
131885            2192761        156566            AV PAULISTA            1793
131898            2192775        156566            AV PAULISTA            1804
134640            2195858        156566            AV PAULISTA            1811
142811            2205026        156566            AV PAULISTA             S/N
144849            2207304        156566            AV PAULISTA            2277
146501            2209140        156566            AV PAULISTA            2000
1537649           6813597        156566            AV PAULISTA            2654
1537652           6813606        156566            AV PAULISTA            2668
1539980           6825222        156566            AV PAULISTA            2424
1544222           6851977        156566            AV PAULISTA            2278
1544232           6852029        156566            AV PAULISTA             S/N
1548284           6872762        156566            AV PAULISTA            1450

In [15]:
matcher.get_full_address_info("AV PAULISTA", '1267aaa')

In [1]:
import folium

In [25]:
mapa = folium.Map(location=[-23.5505, -46.6333], zoom_start=14, tiles="OpenStreetMap")
mapa

In [26]:
mapa = folium.Map(location=[-23.5505, -46.6333], zoom_start=14, tiles=None)

folium.WmsTileLayer(
    url="https://wms.geosampa.prefeitura.sp.gov.br/geoserver/geoportal/ows",
    layers="geoportal:MapaBase_Politico",
    fmt="image/png",
    transparent=True,
    version="1.1.1",
    #crs="EPSG:4326",
    attr="GeoSampa"
).add_to(mapa)

mapa.save("mapa_geosampa.html")

In [27]:
mapa